package com.example.heat.util.enumerian

enum class Cuisine {
    African,
    American,
    British,
    Cajun,
    Caribbean,
    Chinese,
    EasternEuropean,
    European,
    French,
    German,
    Greek,
    Indian,
    Irish,
    Italian,
    Japanese,
    Jewish,
    Korean,
    LatinAmerican,
    Mediterranean,
    Mexican,
    MiddleEastern,
    Nordic,
    Southern,
    Spanish,
    Thai,
    Vietnamese
}